### ISSUE TITLE
Make it possible to watch particular items

### ISSUE THREAD

**Issue by tchap** [tchap/steemwatch#1]
By complexring:

> steemwatch looks good. a suggestion is to 'watch' items that you have commented on or a particular story that you are interested in.  for instance, with my 'interactive cryptography class' -- i'd like to know if anyone has questions, and / or answered an exercise or 2.

**Comment by matthewniemerg** [comment]
thanks.  i think this can be done in one of two ways: 

1) you can have users manually input the link tag (probably not the best way of going about it, as it is prone to human error)
2) have the user input the url to the post, then the backend can parse it appropriately. (preferable option)

**Comment by tchap** [comment]
Yeah, that should not be too hard. The only question is the granularity, e.g. we can have the option to follow the whole post and receive a notification every time a comment is added, or to just follow certain comment thread. Well, I think that just following all comments on a post is much easier to implement and probably enough, what do you think @matthewniemerg ?

**Comment by matthewniemerg** [comment]
i think you can have it so that people could get notifications for a comment directly under them in the reply tree.

Ancestor Post by A
-- Child A1 of A
-- Child A2 of A
-- Child A3 of A
---- Child A3_1 of A3
---- Child A3_2 of A3
-- Child A4 of A
-- Child A5 of A
---- Child A5_1 of A5
---- Child A5_2 of A5
------- Child A5_2_1 of A5_2
------- Child A5_2_2 of A5_2

Now, say you are A.  I would think you would want to be notified by comments from A1,A2,A3,A4,A5.

In addition, you should be able to make a child monitor any comments made directly under the child.

For in stance, if you are A5, you would want to be notified by A5_1 and A5_2, and NOT (A5_2_1 and A5_2_2), unless this was specified.

Something along the lines of having an option of how often to send an alert could be done if monitoring an entire post.

**Comment by tchap** [comment]
So basically to specify a node in the tree along with the depth to watch, where you can specify any positive integer or just the option to watch all children for the given node.

**Comment by matthewniemerg** [comment]
yup.

**Comment by tchap** [comment]
The front-end + server part is implemented, now I have to teach the block processor to emit the event and send it out...

**Comment by tchap** [comment]
Implemented, will release it tomorrow.

**Comment by tchap** [comment]
Actually I already deployed it. It is available on the Events screen, the last section.
